package com.example.dllo.yohomix.sqlgreendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dllo.yohomix.sqlgreendao.YoHoColumns;
import com.example.dllo.yohomix.sqlgreendao.YoHoNew;

import com.example.dllo.yohomix.sqlgreendao.YoHoColumnsDao;
import com.example.dllo.yohomix.sqlgreendao.YoHoNewDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig yoHoColumnsDaoConfig;
    private final DaoConfig yoHoNewDaoConfig;

    private final YoHoColumnsDao yoHoColumnsDao;
    private final YoHoNewDao yoHoNewDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        yoHoColumnsDaoConfig = daoConfigMap.get(YoHoColumnsDao.class).clone();
        yoHoColumnsDaoConfig.initIdentityScope(type);

        yoHoNewDaoConfig = daoConfigMap.get(YoHoNewDao.class).clone();
        yoHoNewDaoConfig.initIdentityScope(type);

        yoHoColumnsDao = new YoHoColumnsDao(yoHoColumnsDaoConfig, this);
        yoHoNewDao = new YoHoNewDao(yoHoNewDaoConfig, this);

        registerDao(YoHoColumns.class, yoHoColumnsDao);
        registerDao(YoHoNew.class, yoHoNewDao);
    }
    
    public void clear() {
        yoHoColumnsDaoConfig.clearIdentityScope();
        yoHoNewDaoConfig.clearIdentityScope();
    }

    public YoHoColumnsDao getYoHoColumnsDao() {
        return yoHoColumnsDao;
    }

    public YoHoNewDao getYoHoNewDao() {
        return yoHoNewDao;
    }

}
